# description of the site (will be placed in meta)
description = "Bridget is a minimal Hugo theme designed for photographers / visual artists."
# use bundled js and css
# * if you want to build the js and css from scratch, set this to false and run `npm install` and `npm run build`
# * tldr: set this to false if you want to edit the js and css
bundled = false
